### ISSUE TITLE
how to make exist web component update  in the markdown code

### ISSUE THREAD

**Issue by metasong** [yhatt/markdown-it-incremental-dom#36]
i'm try to make web components get updated, but no result.
google incremental dom has demo:
http://google.github.io/incremental-dom/#using-with-web-components
but hwo to make the an web component used in markdonw-it.

for example:
I have an i-toc web component and when input it in markdown-it source: <i-toc></i-toc>
it can be showed and works at the first time, and when i try to edit the other part of the document, the markdown-it could not show the <i-toc> component.

to test it we need to enable html tag in markdown-it, and could using this example:
https://github.com/mdn/web-components-examples/tree/master/word-count-web-component
https://developer.mozilla.org/en-US/docs/Web/Web_Components

**Comment by yhatt** [comment]
At present, we cannot indicate how to resolve because there are no clues to point out the problems *in your code*.

GitHub issue tracker is for manage the problems about our plugin, *not for questions.* We also cannot even know whether the cause of reported issue has in the our plugin.
